name: Bug report
description: Report an issue with GKD
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写这个 Bug 报告
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 一些验证
      description: 在提交问题之前，请确保您完成以下操作
      options:
        - label: 搜索检查是否已经存在请求相同功能的问题/讨论，以避免重复创建问题
          required: true
        - label: |
            检查这个问题是属于 [规则](https://github.com/gkd-kit/subscription) 还是属于 GKD 本身, 也许你应该去 [subscription/issues](https://github.com/gkd-kit/subscription/issues) 提交问题
          required: true
        - label: 1.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
          required: true
        - label: 2.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
          required: true
        - label: 3.我确认知晓并同意维护者直接关闭不符合 issue 规范的问题
          required: true
        - label: 我已确保提供下列的日志和BUG描述及其复现步骤, 否则我同意维护者直接关闭问题
          required: true
  - type: textarea
    id: log-file
    attributes:
      label: |
        日志文件-无论什么问题不包含日志将会被直接关闭
      description: |
        主页-设置-日志, 上传日志文件或者生成链接并粘贴到下面的输入框\
        无论什么问题,你都需要提供日志文件. 没有日志, 纯发文字/截图/视频都是没有用的\
    validations:
      required: true
  - type: textarea
    id: bug-1
    attributes:
      label: |
        BUG描述(文字/截图/视频)
      description: |
        请使用尽量准确的描述, 否则你的问题将会被直接关闭
    validations:
      required: true
  - type: textarea
    id: bug-2
    attributes:
      label: |
        期望行为(文字/截图/视频)
      description: |
        请使用尽量准确的描述, 否则你的问题将会被直接关闭
    validations:
      required: true
  - type: textarea
    id: bug-3
    attributes:
      label: |
        实际行为(文字/截图/视频)
      description: |
        请使用尽量准确的描述, 否则你的问题将会被直接关闭
    validations:
      required: true

